package com.example.huerto_hogar.repository

import com.example.huerto_hogar.data.UserDao
import com.example.huerto_hogar.data.UserEntity
import kotlinx.coroutines.flow.Flow

enum class RegistrationResult {
    SUCCESS,
    EMAIL_ALREADY_EXISTS,
    ERROR
}

enum class DeletionResult {
    SUCCESS,
    USER_NOT_FOUND,
    ERROR
}

class UserRepository(private val userDao: UserDao) {

    suspend fun registerUser(entity: UserEntity): RegistrationResult {
        // Id is autogenerated so is difficult to validate
        // So we are going to validate if the email already exists
        val emailExist = userDao.doesEmailExist(entity.email)

        if (emailExist) {
            return RegistrationResult.EMAIL_ALREADY_EXISTS
        }

        return try {
            userDao.createUser(entity)
            RegistrationResult.SUCCESS
        } catch (e: Exception) {
            RegistrationResult.ERROR
        }
    }

    suspend fun deleteUser(entity: UserEntity): DeletionResult {
        // Now we validate that the user we are looking for exists by his email
        val existingUser = userDao.getUserByEmail(entity.email)

        if (existingUser == null) {
            DeletionResult.USER_NOT_FOUND
        }

        return try {
            userDao.deleteUser(entity)
            DeletionResult.SUCCESS
        } catch (e: Exception) {
            DeletionResult.ERROR
        }

    }

    val getAllUsers: Flow<List<UserEntity>> = userDao.listUsers()

}